language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-myyogenerator' ]; then cd .. && eval "mv $currentfolder generator-myyogenerator" && cd generator-myyogenerator; fi

